name: ecom_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0' # Corrected SDK constraint to a range

dependencies:
  flutter:
    sdk: flutter

  # Core UI and state management packages
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2

  # A powerful HTTP client for Dart
  dio: ^5.4.1

  # For local storage of app data
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_analytics: ^12.0.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Asset management for images and fonts
  assets:
    - assets/images/

  # A custom font, like Poppins, can be added here
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
